name: CI/CD CRUD Kesehatan

on:
  push:
    branches:
      - main  # Pastikan ada spasi dan strip (-) sebelum nama branch [cite: 44, 47]

jobs:
  deploy:
    runs-on: ubuntu-latest  # [cite: 50]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # [cite: 53]

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3  # [cite: 55]
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # [cite: 57, 127]

      - name: Deploy ke EC2
        run: |
          # Gunakan alamat IP Public Anda secara langsung [cite: 60, 216]
          ssh -o StrictHostKeyChecking=no ubuntu@108.136.125.120 << 'EOF'
            cd /var/www/TUGAS4  # Folder project di server [cite: 61, 209]
            git pull origin main  # [cite: 62]
            sudo systemctl restart nginx  # [cite: 63, 207]
          EOF